[package]
name = "rust-tcp-server"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lampaBiurkowa/yocto-rust-tcp-server.git"
description = "based on Yocto Project Virtual Summit 2020 demo"

[dependencies]
rusqlite = "0.31.0"